# Generated by Django 3.1.1 on 2021-07-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rruser',
            managers=[
            ],
        ),
    ]
