# Generated by Django 3.1.1 on 2021-07-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210714_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='rruser',
            name='title',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
