# Generated by Django 3.1.1 on 2021-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rruser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rruser',
            name='title',
            field=models.CharField(choices=[('m', 'member'), ('j', 'judge'), ('c', 'staff'), ('p', 'pending')], default='Pending', max_length=50),
        ),
    ]
