# Generated by Django 3.1.1 on 2021-07-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210716_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rruser',
            name='title',
        ),
    ]
