# Generated by Django 3.1.1 on 2021-07-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210716_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestDuet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BestGroupSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BestSolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormsActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_registration', models.BooleanField(default=True)),
                ('judge_registration', models.BooleanField(default=True)),
                ('entry_form', models.BooleanField(default=True)),
                ('contender_reggistration', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(default='Member', max_length=30)),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='member_images')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.img', upload_to='main_image')),
            ],
        ),
    ]
