# Generated by Django 3.1.1 on 2021-07-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_bestduet_bestgroupsong_bestsolo_formsactivation_member_welcomebanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsactivation',
            old_name='contender_reggistration',
            new_name='contender_registration',
        ),
    ]
