# Generated by Django 3.1.1 on 2021-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0002_auto_20210715_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='submission_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
