# Generated by Django 3.1.1 on 2021-07-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0003_auto_20210715_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
