# Generated by Django 3.1.1 on 2021-07-16 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compi', '0005_auto_20210716_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('disqualified', 'Disqualified'), ('passed', 'Passed'), ('failed', 'Failed'), ('ongoing', 'ongoing')], default='Ongoing', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status_comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
