# Generated by Django 3.1.1 on 2021-07-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0006_auto_20210716_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compi.criteria'),
        ),
    ]
