# Generated by Django 3.1.1 on 2021-07-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0007_score_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
