# Generated by Django 3.1.1 on 2021-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0008_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='title',
            field=models.CharField(choices=[('member', 'member'), ('judge', 'judge'), ('staff', 'staff'), ('pending', 'pending')], default='Pending', max_length=50),
        ),
    ]
