# Generated by Django 3.1.1 on 2021-07-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0010_remove_judge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
