# Generated by Django 3.1.1 on 2021-07-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compi', '0011_auto_20210717_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='need_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compi.entry')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compi.judge')),
            ],
        ),
    ]
