# Generated by Django 3.1.1 on 2021-07-17 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compi', '0012_auto_20210717_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compi.competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contender',
            name='smule_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
